### ISSUE TITLE
Can't disable RSS icon

### ISSUE THREAD

**Issue by felixlinker** [nishanths/cocoa-hugo-theme#119]
Hi there,

I'd really like to use your hugo-theme but I can't get the RSS icon to disappear. This is how my `config.toml` looks like:

```toml
baseURL = "https://felixlinker.github.io/"
languageCode = "en-us"
title = "Felix Linker"
theme = "cocoa"
author = "Felix Linker"
RSSLink = false

[[menu.main]]
name = "Works & Publications"
weight = -100
identifier = "works"
url = "/works/"

[params]
author = "Felix Linker"
description = "Some information about Felix Linker"
selfintro = "Student of M.Sc. Computer Science and B.A Philosophy"
github = "https://github.com/felixlinker"
facebook = "https://www.facebook.com/felix.linker"
twitter = "https://twitter.com/felixlinker"
avatar = "img/avatar.jpg"
```

I also tried setting `RSSlin = ""`, setting it in the `[params]` section and did the same for `rsslink`. Neither of thoses attempts worked. This .html code is always added:

```html
<a href="http://localhost:1313/index.xml">
    <img class="icon" src="/img/rss.svg" alt="rss">
</a>
```
